### ISSUE TITLE
Rename Babylonian to SquareRoot.

### ISSUE THREAD

**Issue by MicahZoltu** [Uniswap/uniswap-lib#1]
https://github.com/Uniswap/uniswap-lib/blob/2e31d2c594caf01f16041cd73d8701c43b87cc16/contracts/libraries/Babylonian.sol#L5

The fact that it uses the Babylonian method is an implementation detail.  SquareRoot is what it does, and that is what should be expressed.  You could call it, `GasEfficientSquareRoot`, at least that more clearly expresses what it does and why someone would want to use it.

**Comment by moodysalem** [comment]
I’m comfortable with Babylonian#sqrt because it’s obvious what it does and how it does it, without being too long. The method by which this library computes sqrt would not change given this naming scheme. We would add a new library and deprecate the old, if we decided to implement a different sqrt method that was strictly better. 

Alternately I considered a method named sqrt in a Math library which would be more flexible to change implementation details, but I don’t want to create a competing Math library for 1 function because then it’s tempting to dump a bunch of other functions in there when we should just lean on ds-math or OZ libraries.
